In [108]:
import numpy as np
a=np.arange(1,13)
print(a)
print("tthis is the reshaped array 3,4",a.reshape(3,-1))
print("this is reshaped into 2,6",a.reshape(2,6))
print("this is reshaped into 2,2,3",a.reshape(2,2,3))
print(a.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]
tthis is the reshaped array 3,4 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
this is reshaped into 2,6 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
this is reshaped into 2,2,3 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [109]:
import numpy as np
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90,100,110,120]])
print("array:",arr)
print("70 number:",arr[1][2])
print(arr[1,2])
print("3rd column:",arr[:,2])
print(arr[:2,2:])
print(arr[1:,:2])

array: [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
70 number: 70
70
3rd column: [ 30  70 110]
[[30 40]
 [70 80]]
[[ 50  60]
 [ 90 100]]


In [110]:
import numpy as np

arr = np.array([15, 42, 8, 73, 29, 55, 6, 88, 34, 61])
print(">30",arr[arr>30])
print("even number",arr[arr%2==0])
print("between 20 60",arr[(arr>20) & (arr<60)])
arr[arr<20]=0
print(arr)
c=np.sum(arr>50)
print(c)

>30 [42 73 55 88 34 61]
even number [42  8  6 88 34]
between 20 60 [42 29 55 34]
[ 0 42  0 73 29 55  0 88 34 61]
4


In [111]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[7,  8,  9],
              [10, 11, 12]])
c=np.vstack((a,b))
d=np.hstack((a,b))
print("vittical stack",c)
print("horizantal stack",d)
print("virtical shape",c.shape)
print("horizantal shape",d.shape)

vittical stack [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
horizantal stack [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
virtical shape (4, 3)
horizantal shape (2, 6)


In [112]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])
b = np.array([2,  4,  6,  8, 10])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(np.dot(a,b))
print(a**2)
print(np.sqrt(b))

[12 24 36 48 60]
[ 8 16 24 32 40]
[ 20  80 180 320 500]
[5. 5. 5. 5. 5.]
1100
[ 100  400  900 1600 2500]
[1.41421356 2.         2.44948974 2.82842712 3.16227766]


In [113]:
import numpy as np
sales = np.array([45, 78, 62, 91, 55, 83, 70, 48, 95, 67, 74, 88])
print(np.sum(sales))
print(np.mean(sales))
print(np.max(sales))
print(np.min(sales))
print(np.std(sales))
print(np.median(sales))
print(np.argmax(sales))
print(np.argmin(sales))

856
71.33333333333333
95
45
15.876257605479811
72.0
8
0


In [114]:
import numpy as np

arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
for x in np.nditer(arr2d):
    print(x,end="")
print("-------------")
for x in np.nditer(arr2d):
    if x>5:
        print(x,end="")
print("-------------")
for x in np.nditer(arr2d):
    print(x**2,end="")

123456789-------------
6789-------------
149162536496481

In [139]:
import numpy as np
grades = np.array([[85, 92, 78, 88],
                   [72, 68, 90, 75],
                   [95, 88, 92, 96],
                   [60, 74, 65, 70],
                   [88, 79, 83, 91]])
for i in grades:
    print(np.mean(i),"  ",end="") 
print("")
print(np.mean(grades,axis=0))
print(np.argmax(grades))
print(np.argmin(np.mean(grades,axis=0)))
for i in grades[0]:
    if i>80:
        print(i,end="")
print("")
min1=np.min(grades)
max1=np.max(grades)
n=(grades-min1)/(max1-min1)
print(n)

85.75   76.25   92.75   67.25   85.25   
[80.  80.2 81.6 84. ]
11
0
859288
[[0.69444444 0.88888889 0.5        0.77777778]
 [0.33333333 0.22222222 0.83333333 0.41666667]
 [0.97222222 0.77777778 0.88888889 1.        ]
 [0.         0.38888889 0.13888889 0.27777778]
 [0.77777778 0.52777778 0.63888889 0.86111111]]


In [141]:
import numpy as np

data = np.array([200, 450, 1200, 800, 350, 950, 100, 600])
min1=np.min(data)
max1=np.max(data)
norm=(data-min1)/(max1-min1)
print(norm)
std=(data-np.mean(data))/np.std(data)
print(std)

[0.09090909 0.31818182 1.         0.63636364 0.22727273 0.77272727
 0.         0.45454545]
[-1.07050498 -0.3685345   1.73737693  0.61422417 -0.64932269  1.03540645
 -1.35129317  0.05264779]


In [159]:
import numpy as np

houses = np.array([
    [1200, 3, 10, 45],
    [1800, 4,  5, 72],
    [ 900, 2, 20, 32],
    [2200, 5,  2, 95],
    [1500, 3,  8, 58],
    [ 800, 2, 25, 28],
    [2500, 5,  1,110],
    [1100, 2, 15, 40],
    [1700, 4,  6, 68],
    [2000, 4,  3, 85]
])
print(houses)
x=houses[:,:3]
y=houses[:,1:]
print(x)
print(y)
print("shape of x",np.shape(x))
print("shape of y",np.shape(y))
havg=np.mean(houses[:,3])
print("the average of the houses ",havg)
exp=np.argmax(houses[:,3:])
print("most expensive house",exp)
bed=houses[:,1:2]
print("more than three bed rooms",bed[bed>3])
min1=np.min(x)
max1=np.max(x)
norl=(x[:,0]-min1)/(max1-min1)
print(norl)


[[1200    3   10   45]
 [1800    4    5   72]
 [ 900    2   20   32]
 [2200    5    2   95]
 [1500    3    8   58]
 [ 800    2   25   28]
 [2500    5    1  110]
 [1100    2   15   40]
 [1700    4    6   68]
 [2000    4    3   85]]
[[1200    3   10]
 [1800    4    5]
 [ 900    2   20]
 [2200    5    2]
 [1500    3    8]
 [ 800    2   25]
 [2500    5    1]
 [1100    2   15]
 [1700    4    6]
 [2000    4    3]]
[[  3  10  45]
 [  4   5  72]
 [  2  20  32]
 [  5   2  95]
 [  3   8  58]
 [  2  25  28]
 [  5   1 110]
 [  2  15  40]
 [  4   6  68]
 [  4   3  85]]
shape of x (10, 3)
shape of y (10, 3)
the average of the houses  63.3
most expensive house 6
more than three bed rooms [4 5 5 4 4]
[0.47979192 0.71988796 0.3597439  0.87995198 0.59983994 0.31972789
 1.         0.43977591 0.67987195 0.79991997]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 10 and the array at index 1 has size 3